#!/usr/bin/env node
/**
 * Self-hosts Playfair Display + Montserrat into public/fonts, and writes
 * src/styles/fonts.css.
 *
 * Google Fonts serves per-unicode-range woff2 subsets already, so the fastest
 * correct route is to take those exact files rather than subsetting locally
 * (which would need fonttools/pyftsubset, not installed here).
 *
 * Requests VARIABLE fonts: one file per unicode-range covers the whole weight
 * axis, instead of one file per weight. The legacy CSS uses Montserrat
 * 300/400/500/600/700/800 and Playfair 400/500/600/700 — a variable face
 * covers all of them in a single download per subset.
 *
 * Only `latin` and `latin-ext` are kept. The site is English; cyrillic and
 * vietnamese subsets would never be fetched by a real visitor anyway (they are
 * gated by unicode-range) but shipping them wastes repo space.
 *
 * Run:  node scripts/fetch_fonts.mjs
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const OUT_DIR = 'public/fonts';
const CSS_OUT = 'src/styles/fonts.css';
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

// A modern browser UA is required or Google serves legacy ttf/woff instead.
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
           '(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

const CSS_URL = 'https://fonts.googleapis.com/css2' +
  '?family=Montserrat:ital,wght@0,100..900;1,100..900' +
  '&family=Playfair+Display:ital,wght@0,400..900;1,400..900' +
  '&display=swap';

mkdirSync(OUT_DIR, { recursive: true });

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();

// Google's CSS comments each block with its subset name: /* latin */
const blocks = [];
const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/gi;
for (const m of css.matchAll(re)) {
  const [, subset, body] = m;
  const get = (p) => (body.match(new RegExp(p + ':\\s*([^;]+);')) || [])[1]?.trim();
  const url = (body.match(/url\(([^)]+)\)/) || [])[1];
  blocks.push({
    subset,
    family: get('font-family')?.replace(/['"]/g, ''),
    style: get('font-style') || 'normal',
    weight: get('font-weight') || '400',
    unicodeRange: get('unicode-range'),
    url,
  });
}

if (!blocks.length) {
  console.error('Parsed zero @font-face blocks — Google may have changed format.');
  process.exit(1);
}

// Montserrat italic is dropped: the legacy CSS has five `.italic` rules and all
// five sit inside Playfair-family titles (.about-title, .cta-title,
// .content-title, .vision-title, .contact-title), and the design system says
// Playfair italic is for pull quotes while Montserrat covers body/UI/labels
// with no italic. Verified: `class="italic"` appears on all 9 pages, always in
// a Playfair heading. That is ~107 KB of repo weight for a face nothing asks for.
const isUnusedItalic = (b) => b.style === 'italic' && b.family === 'Montserrat';

const kept = blocks.filter((b) => KEEP_SUBSETS.has(b.subset) && !isUnusedItalic(b));
const slug = (b) =>
  `${b.family.toLowerCase().replace(/\s+/g, '-')}-${b.style}-${b.subset}.woff2`;

let total = 0;
const faces = [];
for (const b of kept) {
  const res = await fetch(b.url, { headers: { 'User-Agent': UA } });
  const buf = Buffer.from(await res.arrayBuffer());
  const name = slug(b);
  writeFileSync(join(OUT_DIR, name), buf);
  total += buf.length;
  faces.push({ ...b, file: name, bytes: buf.length });
  console.log(`  ${name.padEnd(44)} ${(buf.length / 1024).toFixed(1).padStart(7)} KB  ` +
              `weight ${b.weight}  ${b.style}`);
}

const header = `/* ============================================================================
   Self-hosted webfonts. Generated by scripts/fetch_fonts.mjs — do not hand-edit.

   No Google Fonts CDN. On the legacy site that stylesheet was render-blocking
   on 7 of 9 pages and cost roughly 2200 ms of LCP; the two pages with a broken
   <head> accidentally proved it by loading ~15 performance points faster (see
   BASELINE.md).

   Variable fonts: one file per unicode-range covers the whole weight axis, so
   Montserrat 300-800 and Playfair 400-700 are two downloads, not ten.
   font-display: swap — text renders immediately in the fallback.
   ========================================================================= */

`;

const faceCss = faces.map((f) => `@font-face {
  font-family: '${f.family}';
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: swap;
  src: url('/fonts/${f.file}') format('woff2');
  unicode-range: ${f.unicodeRange};
}`).join('\n\n');

writeFileSync(CSS_OUT, header + faceCss + '\n');

console.log(`\n${faces.length} faces, ${(total / 1024).toFixed(1)} KB total → ${OUT_DIR}`);
console.log(`Wrote ${CSS_OUT}`);
const fams = [...new Set(faces.map((f) => `${f.family} ${f.style} ${f.weight}`))];
fams.forEach((f) => console.log(`  ${f}`));
