#!/usr/bin/env node
/**
 * Emits src/pages/*.astro from the extraction manifest. Step 2 only.
 *
 * Body/head/tail regions are imported with Vite's `?raw` and rendered via
 * `set:html`, which in a static build is plain string interpolation into the
 * output — so the emitted HTML is byte-identical to the legacy files, and no
 * content passes through JSX parsing (these pages contain `{` in their inline
 * scripts, which a naive template paste would corrupt).
 *
 * These files are deliberately throwaway: steps 7-8 replace every one of them
 * with real markup built from the design system.
 *
 * Run:  node scripts/extract_legacy.mjs && node scripts/generate_pages.mjs
 */
import { readFileSync, writeFileSync, mkdirSync, statSync } from 'node:fs';

const recs = JSON.parse(readFileSync('src/content/legacy/pages.json', 'utf8'));
mkdirSync('src/pages', { recursive: true });

const nonEmpty = (p) => { try { return statSync(p).size > 1; } catch { return false; } };
const s = (v) => JSON.stringify(v);

for (const r of recs) {
  const hasHead = nonEmpty(`src/content/legacy/head/${r.page}.html`);
  const hasTail = nonEmpty(`src/content/legacy/tail/${r.page}.html`);

  const imports = [
    `import Layout from '../layouts/Layout.astro';`,
    `import body from '../content/legacy/body/${r.page}.html?raw';`,
    hasHead ? `import head from '../content/legacy/head/${r.page}.html?raw';` : null,
    hasTail ? `import tail from '../content/legacy/tail/${r.page}.html?raw';` : null,
  ].filter(Boolean).join('\n');

  const props = [
    `  title={${s(r.title)}}`,
    `  description={${s(r.description)}}`,
    `  canonical={${s(r.canonical)}}`,
    `  ogTitle={${s(r.ogTitle)}}`,
    `  ogDescription={${s(r.ogDescription)}}`,
    `  ogUrl={${s(r.ogUrl)}}`,
    `  twitterTitle={${s(r.twitterTitle)}}`,
    `  twitterDescription={${s(r.twitterDescription)}}`,
    r.activeNav ? `  activeNav={${s(r.activeNav)}}` : null,
    r.bodyClass ? `  bodyClass={${s(r.bodyClass)}}` : null,
    r.footerId ? `  footerId={${s(r.footerId)}}` : null,
    `  pagesCss={${r.pagesCss}}`,
  ].filter(Boolean).join('\n');

  const slots = [
    hasHead ? `  <Fragment slot="head" set:html={head} />` : null,
    `  <Fragment set:html={body} />`,
    hasTail ? `  <Fragment slot="tail" set:html={tail} />` : null,
  ].filter(Boolean).join('\n');

  const note = r.descriptionWasMalformed
    ? `\n// NOTE: the legacy file was missing its opening <meta name="description"\n` +
      `// tag, which force-closed <head>. The text is preserved verbatim; the tag\n` +
      `// is now well-formed. This is the one sanctioned deviation — PARITY.md §4.`
    : '';

  writeFileSync(
    `src/pages/${r.page}.astro`,
    `---\n// GENERATED by scripts/generate_pages.mjs — do not hand-edit.\n` +
    `// Step 2 lift-and-shift. Replaced in steps 7-8.${note}\n${imports}\n---\n\n` +
    `<Layout\n${props}\n>\n${slots}\n</Layout>\n`
  );
}

console.log(`Generated ${recs.length} pages → src/pages/`);
